'use client'

import { useState } from 'react'
import {
  Camera, Dumbbell, Zap, BarChart3, Trophy, ChevronRight,
  Check, Star, Flame, ArrowRight, Smartphone, Globe,
} from 'lucide-react'

const FEATURES = [
  {
    icon: Camera,
    title: 'Snap & Track',
    titleEs: 'Foto y Listo',
    desc: 'Take a photo of your meal. AI instantly calculates calories, protein, carbs, and fat.',
    descEs: 'Toma una foto de tu comida. La IA calcula calorías, proteína, carbos y grasa al instante.',
    color: 'bg-emerald-50 text-emerald-600',
  },
  {
    icon: Dumbbell,
    title: 'AI Workout Plans',
    titleEs: 'Planes de Entrenamiento IA',
    desc: 'Personalized training programs for your goals. Push/Pull/Legs, Full Body, Functional — all generated by AI.',
    descEs: 'Programas personalizados para tus objetivos. Push/Pull/Legs, Full Body, Funcional — generados por IA.',
    color: 'bg-blue-50 text-blue-600',
  },
  {
    icon: Zap,
    title: 'Bidirectional Sync',
    titleEs: 'Sincronización Bidireccional',
    desc: 'Heavy leg day? Your macros adjust automatically. Low on protein for 3 days? Training volume decreases.',
    descEs: 'Día pesado de pierna? Tus macros se ajustan automáticamente. 3 días bajo en proteína? El volumen baja.',
    color: 'bg-amber-50 text-amber-600',
  },
  {
    icon: BarChart3,
    title: 'Track Progress',
    titleEs: 'Registra tu Progreso',
    desc: 'Weight charts, macro history, workout volume, streaks, and badges. See your transformation.',
    descEs: 'Gráficas de peso, historial de macros, volumen de entrenamiento, rachas y badges.',
    color: 'bg-purple-50 text-purple-600',
  },
]

const PRICING = [
  {
    name: 'Free',
    price: '$0',
    period: '',
    features: [
      '3 food photos/day',
      'Manual meal logging',
      '1 AI workout plan',
      'Basic macro tracking',
      '7-day history',
    ],
    featuresEs: [
      '3 fotos de comida/día',
      'Log manual de comidas',
      '1 plan de entrenamiento IA',
      'Tracking básico de macros',
      'Historial de 7 días',
    ],
    cta: 'Get Started',
    ctaEs: 'Comenzar',
    highlight: false,
  },
  {
    name: 'Pro',
    price: '$4.99',
    priceUs: '$9.99',
    period: '/mo',
    features: [
      'Unlimited food photos',
      'GPT-4o vision (higher accuracy)',
      'Unlimited AI plans',
      'Sync Engine',
      'Full history & charts',
      'Progress photos',
    ],
    featuresEs: [
      'Fotos ilimitadas',
      'Visión GPT-4o (mayor precisión)',
      'Planes IA ilimitados',
      'Sync Engine',
      'Historial completo + gráficas',
      'Fotos de progreso',
    ],
    cta: 'Start Free Trial',
    ctaEs: 'Prueba Gratuita',
    highlight: true,
  },
  {
    name: 'Elite',
    price: '$9.99',
    priceUs: '$19.99',
    period: '/mo',
    features: [
      'Everything in Pro',
      'AI Coach (interactive chat)',
      'Multi-model vision',
      'Advanced analytics',
      'Export data',
      'Priority support',
    ],
    featuresEs: [
      'Todo de Pro',
      'Coach IA (chat interactivo)',
      'Visión multi-modelo',
      'Analytics avanzado',
      'Exportar datos',
      'Soporte prioritario',
    ],
    cta: 'Start Free Trial',
    ctaEs: 'Prueba Gratuita',
    highlight: false,
  },
]

const TESTIMONIALS = [
  { name: 'Carlos M.', role: 'Gym Enthusiast', text: 'Finally, an app that adjusts my macros based on what I actually did in the gym. Game changer.', textEs: 'Por fin una app que ajusta mis macros basado en lo que hice en el gym. Game changer.' },
  { name: 'Ana R.', role: 'Fitness Coach', text: 'The bidirectional sync is what I always wanted for my clients. Nutrition and training connected.', textEs: 'La sincronización bidireccional es lo que siempre quise para mis clientes.' },
  { name: 'David L.', role: 'Bodybuilder', text: 'The food recognition is surprisingly accurate, even with Latin American food. Love it.', textEs: 'El reconocimiento de comida es sorprendentemente preciso, incluso con comida latina.' },
]

export function FitSyncLanding() {
  const [lang, setLang] = useState<'en' | 'es'>('en')
  const t = (en: string, es: string) => lang === 'en' ? en : es

  return (
    <div className="min-h-screen bg-white text-gray-900 font-sans">
      {/* ─── Nav ──────────────────────────────────────────────── */}
      <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-xl border-b border-gray-100">
        <div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-emerald-500 flex items-center justify-center">
              <Flame size={18} className="text-white" />
            </div>
            <span className="font-bold text-lg">FitSync AI</span>
          </div>
          <div className="flex items-center gap-4">
            <button
              onClick={() => setLang(lang === 'en' ? 'es' : 'en')}
              className="flex items-center gap-1 text-sm text-gray-500 hover:text-gray-900"
            >
              <Globe size={14} />
              {lang === 'en' ? 'ES' : 'EN'}
            </button>
            <a href="/login" className="text-sm text-gray-600 hover:text-gray-900">
              {t('Log in', 'Entrar')}
            </a>
            <a href="/fitsync" className="px-4 py-2 bg-emerald-500 text-white text-sm font-medium rounded-full hover:bg-emerald-600 transition-colors">
              {t('Get Started', 'Comenzar')}
            </a>
          </div>
        </div>
      </nav>

      {/* ─── Hero ─────────────────────────────────────────────── */}
      <section className="pt-20 pb-16 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-emerald-50 text-emerald-700 rounded-full text-sm font-medium mb-6">
            <Zap size={14} />
            {t('The first app with bidirectional sync', 'La primera app con sincronización bidireccional')}
          </div>

          <h1 className="text-5xl md:text-7xl font-bold tracking-tight leading-[1.1] mb-6">
            {t('Your nutrition and training,', 'Tu nutrición y tu entrenamiento,')}
            <br />
            <span className="text-emerald-500">{t('synced by AI', 'sincronizados por IA')}</span>
          </h1>

          <p className="text-xl text-gray-500 max-w-2xl mx-auto mb-10 leading-relaxed">
            {t(
              'Snap a photo of your meal. Get instant macros. Your workout plan adjusts automatically. No other app does this.',
              'Toma una foto de tu comida. Obtén macros al instante. Tu plan de entrenamiento se ajusta automáticamente. Ninguna otra app hace esto.'
            )}
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a
              href="/fitsync"
              className="inline-flex items-center justify-center gap-2 px-8 py-4 bg-emerald-500 text-white text-lg font-semibold rounded-full hover:bg-emerald-600 transition-colors shadow-lg shadow-emerald-500/25"
            >
              {t('Start Free', 'Comenzar Gratis')}
              <ArrowRight size={20} />
            </a>
            <a
              href="#features"
              className="inline-flex items-center justify-center gap-2 px-8 py-4 bg-gray-100 text-gray-700 text-lg font-medium rounded-full hover:bg-gray-200 transition-colors"
            >
              {t('See How It Works', 'Ver Cómo Funciona')}
            </a>
          </div>

          {/* Phone mockup placeholder */}
          <div className="mt-16 mx-auto max-w-sm">
            <div className="bg-gray-50 rounded-[2rem] p-3 shadow-2xl shadow-gray-200/50">
              <div className="bg-white rounded-[1.5rem] overflow-hidden">
                <div className="bg-emerald-500 p-6 text-white text-center">
                  <Flame size={32} className="mx-auto mb-2" />
                  <p className="text-3xl font-bold">1,450</p>
                  <p className="text-emerald-100 text-sm">{t('kcal remaining', 'kcal restantes')}</p>
                </div>
                <div className="p-4 space-y-3">
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm"><span className="text-gray-500">{t('Protein', 'Proteína')}</span><span>95/160g</span></div>
                    <div className="h-2 bg-gray-100 rounded-full"><div className="h-full bg-blue-500 rounded-full" style={{ width: '59%' }} /></div>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm"><span className="text-gray-500">{t('Carbs', 'Carbos')}</span><span>120/250g</span></div>
                    <div className="h-2 bg-gray-100 rounded-full"><div className="h-full bg-amber-500 rounded-full" style={{ width: '48%' }} /></div>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm"><span className="text-gray-500">{t('Fat', 'Grasa')}</span><span>35/65g</span></div>
                    <div className="h-2 bg-gray-100 rounded-full"><div className="h-full bg-rose-500 rounded-full" style={{ width: '54%' }} /></div>
                  </div>
                </div>
                <div className="border-t border-gray-100 p-4">
                  <div className="flex items-center gap-2 text-sm">
                    <Zap size={14} className="text-emerald-500" />
                    <span className="text-gray-500">{t('Sync: Heavy leg day → +20% carbs', 'Sync: Día pesado piernas → +20% carbos')}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ─── How the Sync Works ───────────────────────────────── */}
      <section className="py-20 px-4 bg-gray-50">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            {t('How Sync Engine Works', 'Cómo Funciona el Sync Engine')}
          </h2>
          <p className="text-gray-500 mb-12 max-w-xl mx-auto">
            {t(
              'Your nutrition and training talk to each other. In real-time.',
              'Tu nutrición y tu entrenamiento se comunican. En tiempo real.'
            )}
          </p>

          <div className="grid md:grid-cols-2 gap-6 text-left">
            <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
              <div className="flex items-center gap-2 mb-4">
                <Dumbbell size={20} className="text-blue-500" />
                <span className="font-semibold">{t('Training → Nutrition', 'Entrenamiento → Nutrición')}</span>
              </div>
              <ul className="space-y-3 text-sm text-gray-600">
                <li className="flex items-start gap-2"><span className="text-blue-500 mt-0.5">●</span>{t('Heavy day (legs, back) → +20% carbs, +15g protein', 'Día pesado (piernas, espalda) → +20% carbos, +15g proteína')}</li>
                <li className="flex items-start gap-2"><span className="text-amber-500 mt-0.5">●</span>{t('Moderate day (push, pull) → +10% carbs', 'Día moderado (push, pull) → +10% carbos')}</li>
                <li className="flex items-start gap-2"><span className="text-gray-400 mt-0.5">●</span>{t('Rest day → -15% carbs, +10g fat', 'Día descanso → -15% carbos, +10g grasa')}</li>
              </ul>
            </div>
            <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
              <div className="flex items-center gap-2 mb-4">
                <Camera size={20} className="text-emerald-500" />
                <span className="font-semibold">{t('Nutrition → Training', 'Nutrición → Entrenamiento')}</span>
              </div>
              <ul className="space-y-3 text-sm text-gray-600">
                <li className="flex items-start gap-2"><span className="text-red-500 mt-0.5">●</span>{t('3 days in deficit → reduce volume 15%', '3 días en déficit → reducir volumen 15%')}</li>
                <li className="flex items-start gap-2"><span className="text-amber-500 mt-0.5">●</span>{t('Low protein 3 days → recovery warning', 'Bajo en proteína 3 días → alerta de recuperación')}</li>
                <li className="flex items-start gap-2"><span className="text-emerald-500 mt-0.5">●</span>{t('Surplus 3 days → increase volume 10%', 'Superávit 3 días → aumentar volumen 10%')}</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Features ─────────────────────────────────────────── */}
      <section id="features" className="py-20 px-4">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              {t('Everything you need', 'Todo lo que necesitas')}
            </h2>
            <p className="text-gray-500">
              {t('Cal AI does half the job. We do it all.', 'Cal AI hace la mitad. Nosotros hacemos todo.')}
            </p>
          </div>
          <div className="grid md:grid-cols-2 gap-6">
            {FEATURES.map((f, i) => (
              <div key={i} className="group p-6 rounded-2xl border border-gray-100 hover:border-gray-200 hover:shadow-lg transition-all">
                <div className={`w-12 h-12 rounded-xl ${f.color} flex items-center justify-center mb-4`}>
                  <f.icon size={24} />
                </div>
                <h3 className="text-xl font-semibold mb-2">{t(f.title, f.titleEs)}</h3>
                <p className="text-gray-500 leading-relaxed">{t(f.desc, f.descEs)}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Stats ────────────────────────────────────────────── */}
      <section className="py-16 px-4 bg-emerald-500 text-white">
        <div className="max-w-4xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
          <div>
            <p className="text-4xl font-bold">200+</p>
            <p className="text-emerald-100 text-sm mt-1">{t('Exercises', 'Ejercicios')}</p>
          </div>
          <div>
            <p className="text-4xl font-bold">12</p>
            <p className="text-emerald-100 text-sm mt-1">{t('Muscle Groups', 'Grupos Musculares')}</p>
          </div>
          <div>
            <p className="text-4xl font-bold">2</p>
            <p className="text-emerald-100 text-sm mt-1">{t('Languages', 'Idiomas')}</p>
          </div>
          <div>
            <p className="text-4xl font-bold">$0</p>
            <p className="text-emerald-100 text-sm mt-1">{t('To Start', 'Para Empezar')}</p>
          </div>
        </div>
      </section>

      {/* ─── Testimonials ─────────────────────────────────────── */}
      <section className="py-20 px-4">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">
            {t('What people say', 'Lo que dicen')}
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            {TESTIMONIALS.map((tm, i) => (
              <div key={i} className="p-6 rounded-2xl bg-gray-50 border border-gray-100">
                <div className="flex gap-1 mb-3">
                  {[...Array(5)].map((_, j) => <Star key={j} size={14} className="fill-amber-400 text-amber-400" />)}
                </div>
                <p className="text-gray-600 text-sm leading-relaxed mb-4">
                  "{t(tm.text, tm.textEs)}"
                </p>
                <div>
                  <p className="font-semibold text-sm">{tm.name}</p>
                  <p className="text-gray-400 text-xs">{tm.role}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Pricing ──────────────────────────────────────────── */}
      <section id="pricing" className="py-20 px-4 bg-gray-50">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">{t('Simple pricing', 'Precios simples')}</h2>
            <p className="text-gray-500">{t('Start free. Upgrade when you need more.', 'Empieza gratis. Mejora cuando necesites más.')}</p>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {PRICING.map((plan, i) => (
              <div
                key={i}
                className={`rounded-2xl p-6 ${
                  plan.highlight
                    ? 'bg-emerald-500 text-white shadow-xl shadow-emerald-500/25 scale-105'
                    : 'bg-white border border-gray-200'
                }`}
              >
                <p className={`text-sm font-medium ${plan.highlight ? 'text-emerald-100' : 'text-gray-500'}`}>
                  {plan.name}
                </p>
                <div className="flex items-baseline gap-1 mt-2 mb-6">
                  <span className="text-4xl font-bold">{plan.price}</span>
                  {plan.period && <span className={plan.highlight ? 'text-emerald-100' : 'text-gray-400'}>{plan.period}</span>}
                </div>
                <ul className="space-y-3 mb-8">
                  {(lang === 'en' ? plan.features : plan.featuresEs).map((f, j) => (
                    <li key={j} className="flex items-start gap-2 text-sm">
                      <Check size={16} className={`mt-0.5 flex-shrink-0 ${plan.highlight ? 'text-emerald-200' : 'text-emerald-500'}`} />
                      <span className={plan.highlight ? 'text-white' : 'text-gray-600'}>{f}</span>
                    </li>
                  ))}
                </ul>
                <a
                  href="/fitsync"
                  className={`block text-center py-3 rounded-xl font-medium transition-colors ${
                    plan.highlight
                      ? 'bg-white text-emerald-600 hover:bg-emerald-50'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  {t(plan.cta, plan.ctaEs)}
                </a>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── CTA ──────────────────────────────────────────────── */}
      <section className="py-20 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            {t('Stop guessing.', 'Deja de adivinar.')}
            <br />
            <span className="text-emerald-500">{t('Start syncing.', 'Empieza a sincronizar.')}</span>
          </h2>
          <p className="text-xl text-gray-500 mb-10">
            {t(
              'Join the first fitness app where nutrition and training actually work together.',
              'Únete a la primera app donde nutrición y entrenamiento realmente trabajan juntos.'
            )}
          </p>
          <a
            href="/fitsync"
            className="inline-flex items-center gap-2 px-10 py-5 bg-emerald-500 text-white text-xl font-semibold rounded-full hover:bg-emerald-600 transition-colors shadow-lg shadow-emerald-500/25"
          >
            {t('Get FitSync AI — Free', 'Obtén FitSync AI — Gratis')}
            <ArrowRight size={24} />
          </a>
        </div>
      </section>

      {/* ─── Footer ───────────────────────────────────────────── */}
      <footer className="py-8 px-4 border-t border-gray-100">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded bg-emerald-500 flex items-center justify-center">
              <Flame size={12} className="text-white" />
            </div>
            <span className="font-semibold text-sm">FitSync AI</span>
          </div>
          <p className="text-sm text-gray-400">
            {t('Built by StratosCore', 'Hecho por StratosCore')} · {new Date().getFullYear()}
          </p>
        </div>
      </footer>
    </div>
  )
}
