-- ══ ContaCR: Plan de Cuentas Estándar Costa Rica ══

INSERT INTO contacr_cuentas_template (codigo, nombre, tipo, naturaleza, nivel, padre_codigo, acepta_movimientos) VALUES
-- 1. ACTIVOS
('1',       'ACTIVOS',                       'activo',     'deudora',   1, NULL,    false),
('1.1',     'Activo Corriente',              'activo',     'deudora',   2, '1',     false),
('1.1.01',  'Efectivo y equivalentes',       'activo',     'deudora',   3, '1.1',   true),
('1.1.02',  'Bancos nacionales',             'activo',     'deudora',   3, '1.1',   true),
('1.1.03',  'Bancos extranjeros',            'activo',     'deudora',   3, '1.1',   true),
('1.1.04',  'Inversiones a corto plazo',     'activo',     'deudora',   3, '1.1',   true),
('1.1.05',  'Cuentas por cobrar',            'activo',     'deudora',   3, '1.1',   true),
('1.1.06',  'Inventarios',                   'activo',     'deudora',   3, '1.1',   true),
('1.1.07',  'IVA crédito fiscal',            'activo',     'deudora',   3, '1.1',   true),
('1.1.08',  'Gastos pagados por anticipado', 'activo',     'deudora',   3, '1.1',   true),
('1.2',     'Activo No Corriente',           'activo',     'deudora',   2, '1',     false),
('1.2.01',  'Terrenos',                      'activo',     'deudora',   3, '1.2',   true),
('1.2.02',  'Edificios',                     'activo',     'deudora',   3, '1.2',   true),
('1.2.03',  'Maquinaria y equipo',           'activo',     'deudora',   3, '1.2',   true),
('1.2.04',  'Mobiliario y equipo oficina',   'activo',     'deudora',   3, '1.2',   true),
('1.2.05',  'Vehículos',                     'activo',     'deudora',   3, '1.2',   true),
('1.2.06',  'Equipo de cómputo',             'activo',     'deudora',   3, '1.2',   true),
('1.2.07',  'Depreciación acumulada',        'activo',     'acreedora', 3, '1.2',   true),

-- 2. PASIVOS
('2',       'PASIVOS',                       'pasivo',     'acreedora', 1, NULL,    false),
('2.1',     'Pasivo Corriente',              'pasivo',     'acreedora', 2, '2',     false),
('2.1.01',  'Cuentas por pagar',             'pasivo',     'acreedora', 3, '2.1',   true),
('2.1.02',  'Documentos por pagar CP',       'pasivo',     'acreedora', 3, '2.1',   true),
('2.1.03',  'IVA débito fiscal',             'pasivo',     'acreedora', 3, '2.1',   true),
('2.1.04',  'Impuesto renta por pagar',      'pasivo',     'acreedora', 3, '2.1',   true),
('2.1.05',  'Cargas sociales por pagar',     'pasivo',     'acreedora', 3, '2.1',   true),
('2.1.06',  'Salarios por pagar',            'pasivo',     'acreedora', 3, '2.1',   true),
('2.1.07',  'Aguinaldo por pagar',           'pasivo',     'acreedora', 3, '2.1',   true),
('2.1.08',  'Vacaciones por pagar',          'pasivo',     'acreedora', 3, '2.1',   true),
('2.2',     'Pasivo No Corriente',           'pasivo',     'acreedora', 2, '2',     false),
('2.2.01',  'Préstamos bancarios LP',        'pasivo',     'acreedora', 3, '2.2',   true),
('2.2.02',  'Documentos por pagar LP',       'pasivo',     'acreedora', 3, '2.2',   true),

-- 3. PATRIMONIO
('3',       'PATRIMONIO',                    'patrimonio', 'acreedora', 1, NULL,    false),
('3.1',     'Capital social',                'patrimonio', 'acreedora', 2, '3',     false),
('3.1.01',  'Capital suscrito y pagado',     'patrimonio', 'acreedora', 3, '3.1',   true),
('3.2',     'Resultados',                    'patrimonio', 'acreedora', 2, '3',     false),
('3.2.01',  'Utilidades acumuladas',         'patrimonio', 'acreedora', 3, '3.2',   true),
('3.2.02',  'Utilidad del período',          'patrimonio', 'acreedora', 3, '3.2',   true),
('3.2.03',  'Pérdidas acumuladas',           'patrimonio', 'deudora',   3, '3.2',   true),

-- 4. INGRESOS
('4',       'INGRESOS',                      'ingreso',    'acreedora', 1, NULL,    false),
('4.1',     'Ingresos operativos',           'ingreso',    'acreedora', 2, '4',     false),
('4.1.01',  'Ventas gravadas (IVA 13%)',     'ingreso',    'acreedora', 3, '4.1',   true),
('4.1.02',  'Ventas exentas',               'ingreso',    'acreedora', 3, '4.1',   true),
('4.1.03',  'Ventas tarifa reducida',        'ingreso',    'acreedora', 3, '4.1',   true),
('4.1.04',  'Servicios profesionales',       'ingreso',    'acreedora', 3, '4.1',   true),
('4.2',     'Otros ingresos',               'ingreso',    'acreedora', 2, '4',     false),
('4.2.01',  'Ingresos financieros',          'ingreso',    'acreedora', 3, '4.2',   true),
('4.2.02',  'Otros ingresos no operativos',  'ingreso',    'acreedora', 3, '4.2',   true),

-- 5. GASTOS
('5',       'GASTOS',                        'gasto',      'deudora',   1, NULL,    false),
('5.1',     'Gastos operativos',             'gasto',      'deudora',   2, '5',     false),
('5.1.01',  'Salarios y jornales',           'gasto',      'deudora',   3, '5.1',   true),
('5.1.02',  'Cargas sociales patronales',    'gasto',      'deudora',   3, '5.1',   true),
('5.1.03',  'Aguinaldos',                    'gasto',      'deudora',   3, '5.1',   true),
('5.1.04',  'Vacaciones',                    'gasto',      'deudora',   3, '5.1',   true),
('5.1.05',  'Alquiler de local',             'gasto',      'deudora',   3, '5.1',   true),
('5.1.06',  'Servicios públicos',            'gasto',      'deudora',   3, '5.1',   true),
('5.1.07',  'Materiales y suministros',      'gasto',      'deudora',   3, '5.1',   true),
('5.1.08',  'Depreciaciones',                'gasto',      'deudora',   3, '5.1',   true),
('5.1.09',  'Seguros',                       'gasto',      'deudora',   3, '5.1',   true),
('5.1.10',  'Mantenimiento y reparaciones',  'gasto',      'deudora',   3, '5.1',   true),
('5.1.11',  'Honorarios profesionales',      'gasto',      'deudora',   3, '5.1',   true),
('5.1.12',  'Publicidad y mercadeo',         'gasto',      'deudora',   3, '5.1',   true),
('5.1.13',  'Gastos de viaje',               'gasto',      'deudora',   3, '5.1',   true),
('5.1.14',  'Papelería y útiles',            'gasto',      'deudora',   3, '5.1',   true),
('5.2',     'Gastos financieros',            'gasto',      'deudora',   2, '5',     false),
('5.2.01',  'Intereses bancarios',           'gasto',      'deudora',   3, '5.2',   true),
('5.2.02',  'Comisiones bancarias',          'gasto',      'deudora',   3, '5.2',   true),
('5.2.03',  'Diferencial cambiario',         'gasto',      'deudora',   3, '5.2',   true),

-- 6. COSTOS
('6',       'COSTOS',                        'costo',      'deudora',   1, NULL,    false),
('6.1',     'Costo de ventas',               'costo',      'deudora',   2, '6',     false),
('6.1.01',  'Compras de mercadería',         'costo',      'deudora',   3, '6.1',   true),
('6.1.02',  'Fletes sobre compras',          'costo',      'deudora',   3, '6.1',   true),
('6.1.03',  'Mano de obra directa',          'costo',      'deudora',   3, '6.1',   true);
